// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import v1beta1 "k8s.io/api/admission/v1beta1"

// Admitter is an autogenerated mock type for the Admitter type
type Admitter struct {
	mock.Mock
}

// Admit provides a mock function with given fields: _a0
func (_m *Admitter) Admit(_a0 v1beta1.AdmissionRequest) (v1beta1.AdmissionResponse, error) {
	ret := _m.Called(_a0)

	var r0 v1beta1.AdmissionResponse
	if rf, ok := ret.Get(0).(func(v1beta1.AdmissionRequest) v1beta1.AdmissionResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(v1beta1.AdmissionResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v1beta1.AdmissionRequest) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
