name: Scheduled CI Check

on:
  schedule:
  - cron: 15 * * * *

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Docker build
        run: make docker

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mv ./kubectl ./bin/
          echo PATH=${PATH}:${GITHUB_WORKSPACE}

      - name: Run e2e tests
        run: make e2e


  # Push image to GitHub Package Registry.
